export function baseTemplate(title: string, content: string, generatedAt: Date): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 12px;
      color: #333;
      line-height: 1.5;
      padding: 20px;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 2px solid #2563eb;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }

    .header h1 {
      color: #2563eb;
      font-size: 24px;
    }

    .header .meta {
      text-align: right;
      font-size: 11px;
      color: #666;
    }

    .section {
      margin-bottom: 25px;
    }

    .section h2 {
      color: #1e40af;
      font-size: 16px;
      margin-bottom: 10px;
      padding-bottom: 5px;
      border-bottom: 1px solid #e5e7eb;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }

    .stat-card {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 15px;
      text-align: center;
    }

    .stat-card .value {
      font-size: 28px;
      font-weight: bold;
      color: #2563eb;
    }

    .stat-card .label {
      font-size: 11px;
      color: #64748b;
      margin-top: 5px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    th, td {
      border: 1px solid #e2e8f0;
      padding: 8px 12px;
      text-align: left;
    }

    th {
      background: #f1f5f9;
      font-weight: 600;
      color: #475569;
    }

    tr:nth-child(even) {
      background: #f8fafc;
    }

    .status {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 10px;
      font-weight: 500;
    }

    .status-available { background: #dcfce7; color: #166534; }
    .status-assigned { background: #dbeafe; color: #1e40af; }
    .status-maintenance { background: #fef3c7; color: #92400e; }
    .status-pending { background: #fef3c7; color: #92400e; }
    .status-approved { background: #dcfce7; color: #166534; }
    .status-rejected { background: #fee2e2; color: #991b1b; }
    .status-completed { background: #dcfce7; color: #166534; }
    .status-in-progress { background: #dbeafe; color: #1e40af; }

    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 10px;
      color: #94a3b8;
    }

    @media print {
      body { padding: 0; }
      .header { page-break-after: avoid; }
      .section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="meta">
      <div>Generated: ${generatedAt.toLocaleDateString()} ${generatedAt.toLocaleTimeString()}</div>
      <div>IVMS Fleet Management System</div>
    </div>
  </div>

  ${content}

  <div class="footer">
    <p>This report was automatically generated by IVMS Fleet Management System</p>
  </div>
</body>
</html>
  `;
}
